MtaServer.Console/Program.cs
MtaServer.Server/MtaServer.cs

- Use exceptions when configuration load fails
- Nullability fixes

Use exceptions when configuration load fails, nullability fixes

---

MtaServer.Console/Program.cs
MtaServer.Packets/Definitions/Commands/ConsoleEchoPacket.cs

adds packet for outputConsole
```csharp
client.SendPacket(new ChatEchoPacket(server.Root.Id, "Hello World", Color.White));
client.SendPacket(new ConsoleEchoPacket("Hello Console World"));
```

outputConsole packet

---

MtaServer.Console/Program.cs
MtaServer.Packets/Definitions/Lua/Rpc/Camera/SetCameraMatrixPacket.cs
MtaServer.Server/Client.cs

Just setCameraMatrix packet iwth test method.
I also added `GenerateSyncTimeContext` which uses mta i don't know why, but i seen multiple classes uses it so i made array of bytes to prevent code duplication

setCameraMatrix

---

MtaServer.Server/Client.cs
MtaServer.Server/MtaServer.cs

fixes multiple bugs concerning disconnecting clients

---

MtaServer.Console/ServerTestLogic.cs
MtaServer.Packets/Definitions/Entities/RemoveEntityPacket.cs

Remove entity packet

---

MtaServer.Console/ServerTestLogic.cs
MtaServer.Packets/Definitions/Lua/ElementRpc/Player/HudComponentVisiblePacket.cs
MtaServer.Server/Elements/Enums/HudComponent.cs
MtaServer.Server/PacketHandling/Factories/PlayerPacketFactory.cs

HudComponentVisible packet with an example

HudComponentVisiblePacket

---

MtaServer.Console/Program.cs
MtaServer.Console/Resources/TestResource/test.lua
MtaServer.Console/ServerTestLogic.cs
MtaServer.Packets.Tests/PacketBuilderTests.cs
MtaServer.Packets/Builder/LuaBuilderExtensions.cs
MtaServer.Packets/Builder/PacketBuilder.cs
MtaServer.Packets/Definitions/Lua/Event/LuaEventPacket.cs
MtaServer.Packets/Definitions/Lua/LuaType.cs
MtaServer.Packets/Definitions/Lua/LuaValue.cs
MtaServer.Packets/Reader/CompressionReaderExtensions.cs
MtaServer.Packets/Reader/LuaReaderExtensions.cs
MtaServer.Packets/Reader/PacketReader.cs
MtaServer.Server/Behaviour/EventLoggingBehaviour.cs
MtaServer.Server/Behaviour/MasterServerAnnouncementBehaviour.cs
MtaServer.Server/Events/LuaEvent.cs
MtaServer.Server/MtaServer.cs
MtaServer.Server/PacketHandling/QueueHandlers/LuaEventQueueHandler.cs

- Packet definition for Lua event packet
- Packet builder and reader extensions for writing / reading Lua values
- Queue handler for reading event packets and triggering an event on `MtaServer`
- Behaviour for logging events triggered

Sending and receiving Lua events

---

MtaServer.Server/Repositories/BasicCompoundElementRepository.cs
MtaServer.Server/Repositories/ElementByIdRepository.cs
MtaServer.Server/Repositories/ElementByTypeRepository.cs
MtaServer.Server/Repositories/FlatElementRepository.cs
MtaServer.Server/Repositories/IElementRepository.cs
MtaServer.Server/Repositories/KdTreeElementRepository.cs

Added element repository optimisation for elements of a certain type within range

Added optimised element tree repository

---

SlipeServer.Server/ResourceServing/BasicHttpServer.cs

before:
"The process cannot access the file"
now:
"Could not bind http server on address http://127.0.0.1:50680/"

Better exception messsage when Http server fail to start.

---

SlipeServer.Packets/Definitions/Join/JoinedGamePacket.cs
SlipeServer.Packets/Definitions/Join/NoSocketPacket.cs
SlipeServer.Server/PacketHandling/QueueHandlers/CommandQueueHandler.cs
SlipeServer.Server/PacketHandling/QueueHandlers/ConnectionQueueHandler.cs
SlipeServer.Server/PacketHandling/QueueHandlers/ExplosionSyncQueueHandler.cs
SlipeServer.Server/PacketHandling/QueueHandlers/LuaEventQueueHandler.cs
SlipeServer.Server/PacketHandling/QueueHandlers/PlayerEventQueueHandler.cs
SlipeServer.Server/PacketHandling/QueueHandlers/RpcQueueHandler.cs
SlipeServer.Server/PacketHandling/QueueHandlers/SyncQueueHandler.cs
SlipeServer.Server/PacketHandling/QueueHandlers/VehicleInOutHandler.cs
SlipeServer.Server/PacketHandling/QueueHandlers/WorkerBasedQueueHandler.cs

Base queue handler instantiates packet classes and reads them instead of individual implementations doing so

Queue handler refactor

---

SlipeServer.ConfigurationProviders/Configurations/XmlConfigurationProvider.cs
SlipeServer.Console/Program.cs
SlipeServer.Packets/Definitions/Join/JoinedGamePacket.cs
SlipeServer.Packets/Definitions/Voice/VoiceDataPacket.cs
SlipeServer.Packets/Definitions/Voice/VoiceEndPacket.cs
SlipeServer.Server/Behaviour/VoiceBehaviour.cs
SlipeServer.Server/Configuration.cs
SlipeServer.Server/Elements/Events/PlayerVoiceEndArgs.cs
SlipeServer.Server/Elements/Events/PlayerVoiceStartArgs.cs
SlipeServer.Server/Elements/Player.cs
SlipeServer.Server/PacketHandling/QueueHandlers/RpcQueueHandler.cs
SlipeServer.Server/PacketHandling/QueueHandlers/VoiceHandler.cs

I made some changes in the repo, but not completed yet they need to be reviewed

Adding voice behaviour

---

SlipeServer.Console/Program.cs
SlipeServer.Console/ServerTestLogic.cs
SlipeServer.Packets.Tests/Packets/ProjectilePacketTests.cs
SlipeServer.Packets/Definitions/Sync/ProjectileSyncPacket.cs
SlipeServer.Server/Configuration.cs
SlipeServer.Server/PacketHandling/QueueHandlers/SyncQueueHandler.cs
SlipeServer.Server/Services/GameWorld.cs

Implements projectiles
Explosion does not happen due "Received unregistered packet PACKET_ID_EXPLOSION"
I've added test command "shootrocket" to shoot them as on the video: https://www.youtube.com/watch?v=kt1Ig53JiEk

Projectiles

---

SlipeServer.Console/Program.cs
SlipeServer.Packets/Definitions/Sync/PlayerBulletSyncPacket.cs
SlipeServer.Packets/Definitions/Sync/WeaponBulletSyncPacket.cs
SlipeServer.Server/PacketHandling/QueueHandlers/SyncQueueHandler.cs

Bullet sync

---

SlipeServer.Console/LuaTestLogic.cs
SlipeServer.Console/SlipeServer.Console.csproj
SlipeServer.Console/test.lua

Move test serverside test lua code to separete file.

---

SlipeServer.Console/ServerTestLogic.cs
SlipeServer.Packets/Definitions/Player/ServerInfoSyncPacket.cs
SlipeServer.Server/MtaServer.cs

adds setmaxplayers command as  well.

Serverinfosync#110

---

SlipeServer.Console/ServerTestLogic.cs
SlipeServer.Packets/Definitions/Lua/Rpc/World/SetGlitchEnabledPacket.cs
SlipeServer.Packets/Enums/GlitchType.cs
SlipeServer.Server/Enums/GlitchType.cs
SlipeServer.Server/Services/GameWorld.cs

setGlitchEnabled

---

SlipeServer.Console/ServerTestLogic.cs
SlipeServer.Packets/Definitions/Player/PlayerNetworkStatusPacket.cs
SlipeServer.Packets/Enums/PlayerNetworkStatusType.cs
SlipeServer.Server/Elements/Events/PlayerNetworkStatusArgs.cs
SlipeServer.Server/Elements/Player.cs
SlipeServer.Server/PacketHandling/QueueHandlers/PlayerEventQueueHandler.cs

I don't know how to test it on local server

PlayerNetworkStatusPacket

---

SlipeServer.Server/Collections/WeaponCollection.cs
SlipeServer.Server/Elements/Player.cs

Clear player weapons on respawn

---

SlipeServer.Console/test.lua
SlipeServer.Lua/LuaTranslator.cs
SlipeServer.Scripting/Definitions/RadarAreaScriptDefinitions.cs
SlipeServer.Server/Elements/RadarArea.cs

RadarArea script definitions

---

SlipeServer.Server/PacketHandling/Handlers/QueueHandlers/ScalingPacketQueueHandler.cs

Helps with identifying what is going wrong

better exception message

---

SlipeServer.Console/Logic/ServerTestLogic.cs
SlipeServer.Server/ElementConcepts/Camera.cs

test command: /camerainterior <0-255>

Implement camera interior along with test command

---

SlipeServer.Server/Elements/Team.cs

Implement IEnumerable for Team #252

---

SlipeServer.Console/Logic/ServerTestLogic.cs
SlipeServer.Packets/Definitions/Lua/ElementRpc/WorldObject/SetWorldObjectScaleRpcPacket.cs
SlipeServer.Server/Behaviour/ObjectPacketBehaviour.cs
SlipeServer.Server/Elements/WorldObject.cs
SlipeServer.Server/PacketHandling/Factories/WorldObjectPacketFactory.cs

Implements SET_OBJECT_SCALE packet and "Scale" property on WorldObject

worldObject Scale property

---

SlipeServer.Packets/Definitions/Sync/ProjectileSyncPacket.cs
SlipeServer.Server/PacketHandling/Handlers/Projectile/ProjectileSyncPacketHandler.cs

- Add source element in projectile sync handler
fixes #189

Add source element to allow for remote projectile creation

---

SlipeServer.Packets/Builder/PacketBuilder.cs
SlipeServer.Packets/Reader/PacketReader.cs

UTF8 encoding for networked strings

---

SlipeServer.Server/AllSeeingEye/AseBehaviour.cs
SlipeServer.Server/AllSeeingEye/AseQueryService.cs
SlipeServer.Server/Behaviour/LocalServerAnnouncementBehaviour.cs
SlipeServer.Server/Behaviour/MasterServerAnnouncementBehaviour.cs
SlipeServer.Server/Constants/NetworkConstants.cs
SlipeServer.Server/ServerOptions/DefaultServerBuilderExtensions.cs

- Local server announcement
- - disable serial verification in ASE since it's unused and won't let users join by double clicking

Local server announcement

---

SlipeServer.Server/MtaServer.cs
SlipeServer.Server/Repositories/RTreeElementRepository.cs

More locking in RTree element repository to prevent crashing issues

---

SlipeServer.Packets.Tests/Packets/VehicleDamageSyncPacketTests.cs
SlipeServer.Packets/Definitions/Transgression/TransgressionPacket.cs
SlipeServer.Packets/Definitions/Vehicles/VehicleDamageSyncPacket.cs
SlipeServer.Packets/Enums/VehicleDoorState.cs
SlipeServer.Packets/Enums/VehicleLightState.cs
SlipeServer.Packets/Enums/VehiclePanel.cs
SlipeServer.Packets/Enums/VehiclePanelState.cs
SlipeServer.Packets/Enums/VehicleWheelState.cs
SlipeServer.Server/Behaviour/VehicleBehaviour.cs
SlipeServer.Server/Elements/Player.cs
SlipeServer.Server/Elements/Vehicle.cs
SlipeServer.Server/PacketHandling/Handlers/Vehicle/Sync/VehicleDamageSyncPacketHandler.cs
SlipeServer.Server/ServerOptions/DefaultServerBuilderExtensions.cs

Vehicle damage sync

---

SlipeServer.Console/Logic/ServerTestLogic.cs
SlipeServer.Packets/Definitions/Vehicles/Enums/UnoccupiedVehicleSyncFlags.cs
SlipeServer.Packets/Definitions/Vehicles/Structs/UnoccupiedVehicleSync.cs
SlipeServer.Packets/Definitions/Vehicles/UnoccupiedVehicleSyncPacket.cs
SlipeServer.Packets/Definitions/Vehicles/UnoccupiedVehicleSyncStartPacket.cs
SlipeServer.Packets/Definitions/Vehicles/UnoccupiedVehicleSyncStopPacket.cs
SlipeServer.Packets/Definitions/Vehicles/VehicleDamageSyncPacket.cs
SlipeServer.Packets/Definitions/Vehicles/VehiclePushSyncPacket.cs
SlipeServer.Server/Behaviour/PedSyncBehaviour.cs
SlipeServer.Server/Behaviour/UnoccupiedVehicleSyncBehaviour.cs
SlipeServer.Server/Configuration.cs
SlipeServer.Server/Elements/Events/VehiclePushedEventArgs.cs
SlipeServer.Server/Elements/Ped.cs
SlipeServer.Server/Elements/Player.cs
SlipeServer.Server/Elements/Vehicle.cs
SlipeServer.Server/PacketHandling/Handlers/Vehicle/Sync/UnoccupiedVehicleSyncPacketHandler.cs
SlipeServer.Server/PacketHandling/Handlers/Vehicle/Sync/VehiclePushSyncPacketHandler.cs
SlipeServer.Server/ServerOptions/DefaultServerBuilderExtensions.cs

Unoccupied vehicle sync, and vehicle push sync

---

azure-pipelines.yml

Multi-platform build pipeline to build windows and linux NetModuleWrapper .dll/.so

---

SlipeServer.Console/Program.cs
SlipeServer.Server/ServerOptions/DefaultServerBuilderExtensions.cs
SlipeServer.Server/ServerOptions/ServerBuilderOptions.cs

Add option to exclude packet handlers, behaviours, services and middlewares from the defaults when using builder.AddDefault

Add option to exclude defaults

---

SlipeServer.Server/Behaviour/VehicleBehaviour.cs
SlipeServer.Server/PacketHandling/Factories/VehiclePacketFactory.cs

Vehicle packet factory fix

---

SlipeServer.Console/Logic/ServerTestLogic.cs
SlipeServer.Packets/Definitions/Lua/ElementRpc/Ped/PedClothesPacket.cs
SlipeServer.Server/Behaviour/PedPacketBehaviour.cs
SlipeServer.Server/PacketHandling/Factories/PedPacketFactory.cs
SlipeServer.Server/PacketHandling/Handlers/Rpc/RpcPacketHandler.cs

Rename clothes packet and send when player joins

---

SlipeServer.Console/Logic/ServerTestLogic.cs
SlipeServer.Packets/Definitions/Vehicles/VehicleResyncPacket.cs
SlipeServer.Server/Behaviour/UnoccupiedVehicleSyncBehaviour.cs
SlipeServer.Server/PacketHandling/Factories/VehiclePacketFactory.cs

Added vehicle resync

---

SlipeServer.Server/Elements/Ped.cs
SlipeServer.Server/Elements/Player.cs

Reset HasJetpack to false when warping into vehicle and spawning

---

SlipeServer.Packets/Constants/PacketSendingConstants.cs
SlipeServer.Server.TestTools/TestingClient.cs
SlipeServer.Server/Client.cs
SlipeServer.Server/Elements/Ped.cs
SlipeServer.Server/Enums/ClientConnectionState.cs

Enforce packets sent during connection sequence are only connection related packets

Enforce packets sent during connection sequence

---

SlipeServer.Console/Logic/ServerTestLogic.cs
SlipeServer.Packets/Definitions/Lua/ElementRpc/Vehicle/SetVehicleFuelTankExplodable.cs
SlipeServer.Server/Behaviour/VehicleBehaviour.cs
SlipeServer.Server/Elements/Vehicle.cs
SlipeServer.Server/PacketHandling/Factories/VehiclePacketFactory.cs

Vehicle fuel tank explodable

---

SlipeServer.Console/Program.cs
SlipeServer.Packets/Definitions/Lua/ElementRpc/WorldObject/SetWorldObjectVisibileInAllDimensionsPacket.cs
SlipeServer.Server/Behaviour/ObjectPacketBehaviour.cs
SlipeServer.Server/Elements/WorldObject.cs
SlipeServer.Server/PacketHandling/Factories/WorldObjectPacketFactory.cs

Set (object) visible in all dimensions packet

---

SlipeServer.Console/Logic/ElementPoolingTestLogic.cs
SlipeServer.Console/Program.cs
SlipeServer.Server.Tests/Unit/Elements/ElementPoolTests.cs
SlipeServer.Server/Elements/ElementPool.cs

Element pool

---

SlipeServer.Packets.Tests/PacketBuilderTests.cs
SlipeServer.Packets/Builder/PacketBuilder.cs
SlipeServer.Packets/Reader/PacketReader.cs
SlipeServer.Server/Events/LuaEvent.cs

Replace bitarray with simple byte array / byte lists, with some performance optimisations when writing byte aligned full bytes

Replace bitarray with simple byte array / byte lists

---

SlipeServer.Packets/Definitions/Join/PlayerQuitPacket.cs
SlipeServer.Packets/Definitions/Sync/PlayerPureSyncPacket.cs
SlipeServer.Server/Client.cs
SlipeServer.Server/Enums/ClientConnectionState.cs
SlipeServer.Server/Extensions/PacketExtensions.cs
SlipeServer.Server/IClient.cs
SlipeServer.Server/MtaServer.cs
SlipeServer.Server/NullClient.cs

Connection state fixes

---

SlipeServer.Server/Resources/Serving/BasicHttpServer.cs

Attempt at handling the HTTP server error messasge in other languages

---

SlipeServer.Console/Logic/ServerTestLogic.cs
SlipeServer.Server/Resources/Resource.cs

Added StartForAsync method

---

SlipeServer.Console/Resources/MetaXmlTestResource/meta.xml
SlipeServer.Console/Resources/MetaXmlTestResource/nocache.lua
SlipeServer.Console/Resources/MetaXmlTestResource/test.lua
SlipeServer.Console/Resources/TestResource/test.lua
SlipeServer.Server/Resources/Interpreters/Meta/MetaXml.cs
SlipeServer.Server/Resources/Interpreters/MetaXmlResourceInterpreter.cs
SlipeServer.Server/Resources/Resource.cs

Added cache=false and export support to meta.xml resource interpreter

---

SlipeServer.Console/Logic/ServerTestLogic.cs
SlipeServer.Packets/Definitions/Lua/ElementRpc/Vehicle/SetVehicleVariantPacket.cs
SlipeServer.Server/Behaviour/VehicleBehaviour.cs
SlipeServer.Server/ElementConcepts/VehicleVariants.cs
SlipeServer.Server/Elements/Vehicle.cs
SlipeServer.Server/PacketHandling/Builders/AddEntityPacketBuilder.cs
SlipeServer.Server/PacketHandling/Factories/VehiclePacketFactory.cs

Vehicle variants

---

SlipeServer.Console/Logic/ServerTestLogic.cs
SlipeServer.Packets/Definitions/Lua/ElementRpc/Vehicle/SetVehicleDamageProofPacket.cs
SlipeServer.Packets/Definitions/Lua/ElementRpc/Vehicle/SetVehicleDoorsDamageProofPacket.cs
SlipeServer.Server/Behaviour/VehicleBehaviour.cs
SlipeServer.Server/Elements/Vehicle.cs
SlipeServer.Server/PacketHandling/Builders/AddEntityPacketBuilder.cs

Vehicle (and vehicle doors) damage proofing

---

SlipeServer.Console/Logic/ServerTestLogic.cs
SlipeServer.Packets/Definitions/Entities/AddEntityPacket.cs
SlipeServer.Packets/Definitions/Entities/Structs/VehicleSirenSet.cs
SlipeServer.Packets/Definitions/Lua/ElementRpc/Vehicle/Sirens/GiveVehicleSirensPacket.cs
SlipeServer.Packets/Definitions/Lua/ElementRpc/Vehicle/Sirens/RemoveVehicleSirensPacket.cs
SlipeServer.Packets/Definitions/Lua/ElementRpc/Vehicle/Sirens/SetVehicleSirensOnPacket.cs
SlipeServer.Packets/Definitions/Lua/ElementRpc/Vehicle/Sirens/SetVehicleSirensPacket.cs
SlipeServer.Packets/Enums/VehicleSirenType.cs
SlipeServer.Server/Behaviour/VehicleBehaviour.cs
SlipeServer.Server/Elements/Events/VehicleSirenUpdatedEventArgs.cs
SlipeServer.Server/Elements/Vehicle.cs
SlipeServer.Server/PacketHandling/Handlers/Vehicle/Sync/VehiclePureSyncPacketHandler.cs

Vehicle sirens

---

SlipeServer.Console/Logic/ServerTestLogic.cs
SlipeServer.Packets/Definitions/Lua/Rpc/World/RemoveWorldModelPacket.cs
SlipeServer.Packets/Definitions/Lua/Rpc/World/RestoreAllWorldModelsPacket.cs
SlipeServer.Packets/Definitions/Lua/Rpc/World/RestoreWorldModelPacket.cs
SlipeServer.Packets/Definitions/Map/MapInfoPacket.cs
SlipeServer.Packets/Definitions/Map/Structs/WorldObjectRemoval.cs
SlipeServer.Server/Behaviour/MapInfoBehaviour.cs
SlipeServer.Server/Services/GameWorld.cs

Remove and restore world models

---

SlipeServer.Console/Elements/CustomPlayer.cs
SlipeServer.Console/Logic/NametagTestLogic.cs
SlipeServer.Console/Logic/ServerTestLogic.cs
SlipeServer.Console/Logic/ServiceUsageTestLogic.cs
SlipeServer.Packets/Definitions/Player/PlayerModInfoPacket.cs
SlipeServer.Packets/Definitions/Sync/KeySyncPacket.cs
SlipeServer.Server.Tests/Integration/Elements/ElementTests.cs
SlipeServer.Server/Behaviour/CollisionShapeBehaviour.cs
SlipeServer.Server/Behaviour/DefaultChatBehaviour.cs
SlipeServer.Server/Behaviour/ElementPacketBehaviour.cs
SlipeServer.Server/Behaviour/PlayerJoinElementBehaviour.cs
SlipeServer.Server/Behaviour/VelocityBehaviour.cs
SlipeServer.Server/ElementCollections/RTreeElementCollection.cs
SlipeServer.Server/ElementConcepts/ElementAttachment.cs
SlipeServer.Server/Elements/Blip.cs
SlipeServer.Server/Elements/ColShapes/CollisionShape.cs
SlipeServer.Server/Elements/Element.cs
SlipeServer.Server/Elements/IdGeneration/BasicElementIdGenerator.cs
SlipeServer.Server/Elements/IdGeneration/CollectionBasedElementIdGenerator.cs
SlipeServer.Server/Elements/Player.cs
SlipeServer.Server/Extensions/ColorExtensions.cs
SlipeServer.Server/Extensions/PacketExtensions.cs
SlipeServer.Server/MtaServer.cs
SlipeServer.Server/PacketHandling/Builders/AddEntityPacketBuilder.cs
SlipeServer.Server/PacketHandling/Factories/AddEntityPacketFactory.cs
SlipeServer.Server/PacketHandling/Handlers/Player/Sync/PlayerPureSyncPacketHandler.cs
SlipeServer.Server/PacketHandling/Handlers/Rpc/RpcPacketHandler.cs
SlipeServer.Server/PacketHandling/Handlers/Vehicle/VehicleInOutPacketHandler.cs

- Turret / hydraulics sync in keysync packet
- Creation of blips from a player constructor
- Element SyncsToAll property
- Removed vehicle enter logging
- Fixed players who are in vehicles not showing up when a player joins
- Concurrency fixes in colshapes

Miscellaenous fixes

---

SlipeServer.Console/Logic/ServerTestLogic.cs
SlipeServer.Packets/Definitions/Player/ShowChatPacket.cs
SlipeServer.Server/Services/ChatBox.cs

Add show chat packet

---

SlipeServer.Console/Logic/ServerTestLogic.cs
SlipeServer.Server/Behaviour/ElementPacketBehaviour.cs

Fix AreCollisionsEnabled and IsCallPropagationEnabled properties

---

SlipeServer.Docs/docfx.json
SlipeServer.Docs/template/styles/main.css
SlipeServer.Server/Elements/ColShapes/CollisionShape.cs
SlipeServer.Server/NullClient.cs
SlipeServer.Server/PacketHandling/Handlers/Player/Sync/PlayerPureSyncPacketHandler.cs

- Player position fix related to contact elements
- More docs
- Preparation for new docfx version with nested namespaces

Player position fix related to contact elements

---

SlipeServer.Console/Logic/ServerTestLogic.cs
SlipeServer.Server/Resources/Resource.cs

make StartForAsync throw an exception when player disconnect

Improvment for StartForAsync

---

SlipeServer.Docs/articles/getting-started/your-first-logic.md

Fixing the this.server.PlayerJoined typo and added the player.Camera.Target = player to make the code functional.

Fixing Code Examples

---

SlipeServer.Packets/Definitions/Sync/PlayerDisconnectPacket.cs
SlipeServer.Server/Clients/Client.cs
SlipeServer.Server/PacketHandling/Handlers/Connection/JoinDataPacketHandler.cs

1. now password is taken from server "Password" property
2. You no longer hang  on "connecting" when entering wrong password
( Probably "Configuration" class should be used only on startup, settings copied to different other classes that later will use them)

Fix server password

---

SlipeServer.Console/Elements/CustomPlayer.cs
SlipeServer.Server/Elements/Element.cs

Feature: Make destroy/create methods on element virtual

---

SlipeServer.Server/Behaviour/MasterServerAnnouncementBehaviour.cs

```
Unhandled exception. System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
---> System.TimeoutException: A task was canceled.
---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionWithTelemetryAsync(HttpRequestMessage request, HttpConnectionPool pool, Boolean async, CancellationToken requestCancellationToken)
at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken …
```

Fix crash in AnnounceToMasterServer

---

SlipeServer.Server/Elements/Player.cs
SlipeServer.Server/PacketHandling/Handlers/Player/Sync/PlayerPureSyncPacketHandler.cs

Implements this piece of mta code:
https://github.com/multitheftauto/mtasa-blue/blob/master/Server/mods/deathmatch/logic/CGame.cpp#L2310-L2320

Fix: Add remaining pure sync code

---

SlipeServer.Console/Program.cs
SlipeServer.Console/SlipeServer.Console.csproj
SlipeServer.Example/ServerBuilderExtensions.cs
SlipeServer.Example/ServerExampleLogic.cs
SlipeServer.Example/SlipeServer.Example.csproj
SlipeServer.HostBuilderExample/Program.cs
SlipeServer.HostBuilderExample/SlipeServer.HostBuilderExample.csproj
SlipeServer.Server/Configuration.cs
SlipeServer.WebHostBuilderExample/Program.cs
SlipeServer.WebHostBuilderExample/SlipeServer.WebHostBuilderExample.csproj
SlipeServer.sln

Because we have 3 ways of running servers then for test purpose we should have same test logic in each of them, thats why i created placehlder project with common logic that later will be moved there.

Add common example project with placeholder for common logic

---

SlipeServer.Net/Wrappers/NetWrapper.cs

Better user experience, you won't get exception like that:

Feature: Prevent starting, stopping net server twice
